class_name IconFont
extends RefCounted

static func get_icon(icon_name: String) -> String:
	match icon_name:
		"play": return "▶"
		"build": return "🔨"
		"library": return "📚"
		"parent": return "🛡"
		"place": return "➕"
		"paint": return "🎨"
		"move": return "✋"
		"duplicate": return "📋"
		"coin": return "🪙"
		"star": return "⭐"
		"flag": return "🚩"
		"undo": return "↩"
		"restore": return "🔧"
		"safe": return "🔒"
		"ai": return "🤖"
		"human": return "👤"
		"check": return "✅"
		"cross": return "❌"
		"warn": return "⚠"
		"settings": return "⚙"
		"time": return "⏱"
		"chart": return "📊"
		"world": return "🌍"
		"template": return "📐"
		"solo": return "🧍"
		"coop": return "🤝"
		"quest": return "📜"
		"map": return "🗺"
		"microphone": return "🎤"
		"sparkle": return "✨"
	return "✦"
